title: ACM Multimedia Reproducibility 2026
email: mkastner@hiroshima-cu.ac.jp
description: > # this means to ignore newlines until "baseurl:"
  ACMMM Reproducibility

# Build settings
markdown: kramdown
kramdown:
  toc_levels: "2,3"
baseurl: "/website"
url: ""
